name: syncspace
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_widget_from_html: ^0.15.2
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  html_editor_enhanced: ^2.6.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/